### ISSUE TITLE
G2P plugin could not be loaded

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/ovos-docker-tts#3]
This morning I tried to reinstall ovos-docker-tts. I with ``docker compose up -d ovos_tts_piper`` and then I found in the logs:

```
2023-08-25 11:56:14.233 - OVOS - ovos_plugin_manager.g2p:create:142 - ERROR - The selected G2P plugin could not be loaded.
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/g2p.py", line 139, in create
    g2p = clazz(g2p_config)
          ^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
2023-08-25 11:56:14.233 - OVOS - ovos_plugin_manager.templates.tts:__init__:448 - ERROR - G2P plugin not loaded, there will be no mouth movements
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/templates/tts.py", line 446, in __init__
    self.g2p = OVOSG2PFactory.create(cfg)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/g2p.py", line 139, in create
    g2p = clazz(g2p_config)
          ^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
2023-08-25 11:56:15.566 - OVOS - ovos_tts_server.__main__:main:46 - INFO - Server Started
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9666 (Press CTRL+C to quit)
```

**Comment by goldyfruit** [comment]
Fixed https://github.com/OpenVoiceOS/ovos-docker-tts/commit/693b53264218bd55675b90e6b69c66a68caa64d2
